# 로컬 개발 환경 설정
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your_google_client_id.apps.googleusercontent.com
            client-secret: your_google_client_secret

app:
  jwt:
    secret: local-development-jwt-secret-key-change-in-production

logging:
  level:
    com.algoroadmap: DEBUG
    org.springframework.web: DEBUG